# Generated by Django 4.0 on 2021-12-14 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='last_notification',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
