# Generated by Django 4.0 on 2021-12-15 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0002_alert_last_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='uid_scheduler',
            field=models.CharField(default='', max_length=255),
        ),
    ]
