# Generated by Django 4.0 on 2021-12-16 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0003_alert_uid_scheduler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='last_notification',
            field=models.DateTimeField(default='2021-12-16T13:55:36.581486'),
        ),
    ]
